sudo: required

language: go

go:
  - 1.8

services:
  - docker

before_install:
  # Dependencies are installed through glide
  - go get -v github.com/Masterminds/glide
  # Test coverage are run on coveralls
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

install:
  - glide install

script:
  - make docker
  - pwd
  - echo $GOPATH
  - $GOPATH/bin/goveralls -service=travis-ci

notifications:
  email: false
